name: Extract Project Version
author: sindre0830
description: Extracts the version from any project files

inputs:
  file_path:
    description: The path to the file to extract the version from
    required: true
  custom_regex:
    description: A custom regex to use for extracting the version

outputs:
  extracted_version:
    description: The extracted version

runs:
  using: node20
  main: dist/index.js
